server:
  port: 8190

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDBDialect

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true         # SQL에 색상 부여 (터미널에서 가독성 향상)
        use_sql_comments: false      # 쿼리에 주석 추가

    show-sql: false

springdoc:
  swagger-ui:
    query-config-enabled: false

logbook:
  filter:
    enabled: false

logging:
  level:
    root: info
    org.zalando.logbook: trace
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.toyproject.board: DEBUG