-- 1. 기존 테이블 및 시퀀스 삭제 (의존성 포함 삭제)
DROP TABLE IF EXISTS public.payment_log CASCADE;
DROP TABLE IF EXISTS public.seat_status_log CASCADE;
DROP TABLE IF EXISTS public.reservation_detail CASCADE;
DROP TABLE IF EXISTS public.reservation CASCADE;
DROP TABLE IF EXISTS public.scheduled_seat CASCADE;
DROP TABLE IF EXISTS public.schedule CASCADE;
DROP TABLE IF EXISTS public.movie CASCADE;
DROP TABLE IF EXISTS public.seat CASCADE;
DROP TABLE IF EXISTS public.theater CASCADE;
DROP TABLE IF EXISTS public.client CASCADE;
DROP TABLE IF EXISTS public.outbox CASCADE;

DROP SEQUENCE IF EXISTS seat_idx_seq;
DROP SEQUENCE IF EXISTS scheduled_seat_idx_seq;
DROP SEQUENCE IF EXISTS reservation_detail_idx_seq;

-- 2. 시퀀스 생성 (Batch Insert 최적화: INCREMENT BY 50)
CREATE SEQUENCE seat_idx_seq START 1 INCREMENT BY 50;
CREATE SEQUENCE scheduled_seat_idx_seq START 1 INCREMENT BY 50;
CREATE SEQUENCE reservation_detail_idx_seq START 1 INCREMENT BY 50;

-- 3. 상영관 (Theater)
CREATE TABLE public.theater (
                                theater_idx     int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                cinema_name     varchar(30)  NOT NULL,
                                theater_name    varchar(30)  NOT NULL,
                                seat_count      int4         NOT NULL,
                                CONSTRAINT theater_pkey PRIMARY KEY (theater_idx)
);

-- 4. 좌석 (Seat) - SEQUENCE 사용
CREATE TABLE public.seat (
                             seat_idx        int8         NOT NULL DEFAULT nextval('seat_idx_seq'),
                             theater_idx     int8         NOT NULL,
                             seat_row        varchar(10)  NOT NULL,
                             seat_column     int4         NOT NULL,
                             CONSTRAINT seat_pkey PRIMARY KEY (seat_idx),
                             CONSTRAINT uk_theater_seat UNIQUE (theater_idx, seat_row, seat_column),
                             CONSTRAINT fk_seat_theater FOREIGN KEY (theater_idx) REFERENCES public.theater(theater_idx)
);

-- 5. 영화 (Movie)
CREATE TABLE public.movie (
                              movie_idx       int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              movie_title     varchar(50)  NOT NULL,
                              release_date    date         NOT NULL,
                              runtime         time         NOT NULL,
                              audience_type   int4         NOT NULL,
                              total_audience  int4         NOT NULL DEFAULT 0,
                              is_deleted      bool         NOT NULL DEFAULT false,
                              rgdt            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              CONSTRAINT movie_pkey PRIMARY KEY (movie_idx)
);

-- 6. 상영 일정 (Schedule)
CREATE TABLE public.schedule (
                                 schedule_idx    int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 movie_idx       int8         NOT NULL,
                                 theater_idx     int8         NOT NULL,
                                 start_at        timestamp(6) NOT NULL,
                                 end_at          timestamp(6) NOT NULL,
                                 ticket_price    int4         NOT NULL,
                                 discount_type   int4         NOT NULL,
                                 CONSTRAINT schedule_pkey PRIMARY KEY (schedule_idx),
                                 CONSTRAINT fk_schedule_movie FOREIGN KEY (movie_idx) REFERENCES public.movie(movie_idx),
                                 CONSTRAINT fk_schedule_theater FOREIGN KEY (theater_idx) REFERENCES public.theater(theater_idx)
);

-- 7. 고객 (Client)
CREATE TABLE public.client (
                               client_idx      int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               email           varchar(100) NOT NULL,
                               password        varchar(255) NOT NULL,
                               phone           varchar(30)  NULL,
                               is_deleted      bool         NOT NULL DEFAULT false,
                               rgdt            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT client_pkey PRIMARY KEY (client_idx),
                               CONSTRAINT uk_client_email UNIQUE (email)
);

-- 8. 일정별 좌석 (Scheduled_Seat) - SEQUENCE 사용
CREATE TABLE public.scheduled_seat (
                                       ss_idx          int8         NOT NULL DEFAULT nextval('scheduled_seat_idx_seq'),
                                       schedule_idx    int8         NOT NULL,
                                       seat_idx        int8         NOT NULL,
                                       client_idx      int8         NULL,
                                       seat_reservation_status int4 NOT NULL,
                                       version         int8         DEFAULT 0,
                                       rgdt            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       CONSTRAINT scheduled_seat_pkey PRIMARY KEY (ss_idx),
                                       CONSTRAINT uk_schedule_seat UNIQUE (schedule_idx, seat_idx),
                                       CONSTRAINT fk_ss_schedule FOREIGN KEY (schedule_idx) REFERENCES public.schedule(schedule_idx),
                                       CONSTRAINT fk_ss_seat FOREIGN KEY (seat_idx) REFERENCES public.seat(seat_idx)
);

-- 9. 예매 (Reservation)
CREATE TABLE public.reservation (
                                    reservation_idx    int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    client_idx         int8         NOT NULL,
                                    reservation_number varchar(50)  NOT NULL,
                                    movie_title        varchar(50)  NOT NULL,
                                    theater_name       varchar(30)  NOT NULL,
                                    total_amount       int4         NOT NULL,
                                    reservation_status int4         NOT NULL,
                                    expired_at         timestamp(6) NOT NULL,
                                    rgdt               timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    CONSTRAINT reservation_pkey PRIMARY KEY (reservation_idx),
                                    CONSTRAINT uk_reservation_number UNIQUE (reservation_number),
                                    CONSTRAINT fk_reservation_client FOREIGN KEY (client_idx) REFERENCES public.client(client_idx)
);

-- 10. 예매 상세 (Reservation_Detail) - SEQUENCE 사용
CREATE TABLE public.reservation_detail (
                                           rd_idx             int8         NOT NULL DEFAULT nextval('reservation_detail_idx_seq'),
                                           reservation_idx    int8         NOT NULL,
                                           ss_idx             int8         NOT NULL,
                                           seat_name          varchar(10)  NOT NULL,
                                           price              int4         NOT NULL,
                                           audience_discount_type int4     NOT NULL,
                                           reservation_detail_status int4  NOT NULL,
                                           rgdt               timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           CONSTRAINT reservation_detail_pkey PRIMARY KEY (rd_idx),
                                           CONSTRAINT uk_rd_ss_idx UNIQUE (ss_idx),
                                           CONSTRAINT fk_rd_reservation FOREIGN KEY (reservation_idx) REFERENCES public.reservation(reservation_idx),
                                           CONSTRAINT fk_rd_ss FOREIGN KEY (ss_idx) REFERENCES public.scheduled_seat(ss_idx)
);

-- 11. 결제 로그 (Payment_Log)
CREATE TABLE public.payment_log (
                                    pl_idx          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    reservation_idx int8         NOT NULL,
                                    pg_id           varchar(255) NOT NULL,
                                    amount          int8         NOT NULL,
                                    payment_type    int4         NOT NULL,
                                    payment_status  int4         NOT NULL,
                                    failure_reason  varchar(255) NULL,
                                    rgdt            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    CONSTRAINT payment_log_pkey PRIMARY KEY (pl_idx),
                                    CONSTRAINT fk_pl_reservation FOREIGN KEY (reservation_idx) REFERENCES public.reservation(reservation_idx)
);

-- 12. 좌석 상태 변경 로그 (Seat_Status_Log)
CREATE TABLE public.seat_status_log (
                                        ssl_idx         int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        ss_idx          int8         NOT NULL,
                                        client_idx      int8         NOT NULL,
                                        seat_reservation_status int4 NOT NULL,
                                        reason          varchar(100) NULL,
                                        rgdt            timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        CONSTRAINT seat_status_log_pkey PRIMARY KEY (ssl_idx)
);
-- 13. outBox 패턴 적용 cdc
CREATE TABLE public.outbox (
                                       id SERIAL PRIMARY KEY,
                                       aggregate_type VARCHAR(255),
                                       aggregate_id BIGINT,
                                       event_type VARCHAR(255),
                                       payload JSONB,
                                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );